### PR TITLE
fix for column seperator

### PR DESCRIPTION
**Pull request by pjaudiomv**
I actually noticed this awhile back and forgot about it, the column separator checkbox wasn't saving values. this fixes that.

### CODE REVIEW

**Comment by pjaudiomv** [comment]
also messed up version on last PR, I didn't realize 1.9.1 wasn't released so I reverted bump to 1.9.2.

**Comment by radius314** [comment]
what is the side effect of this bug?

**Comment by pjaudiomv** [comment]
column separator checkbox Not saving values, so Colin separator won't display. If it is existing it works but if not no dice

**Comment by radius314** [comment]
Are you talking about the line in between the columns?

**Comment by pjaudiomv** [comment]
Correct

**Pull request merged**
