### PR TITLE
fix for #69

### PR DESCRIPTION
**Pull request by pjaudiomv**
ref #69

### CODE REVIEW

**Comment by radius314** [comment]
I think it would be better to replace `[city]` with the city, rather than relying on sequencing.  Am I missing something?

**Comment by pjaudiomv** [comment]
The city is being replaced with city. The group short code was being 'set' after the city one so worked fine however if you used meeting_name it wouldn't. If I moved group above city it would cause same issue. There's already a bunch of sequencing in place. meeting_name and group should be together

**Comment by radius314** [comment]
What if the name of the group was "Sunday commentary"?

**Comment by pjaudiomv** [comment]
Yea that'd be a problem. Good point.

**Comment by radius314** [comment]
Why are we not doing find and replace on the actual shortcode text with the brackets.  That way there would never be a mistake.

**Comment by pjaudiomv** [comment]
Because the brackets are not used, this would mess up most meetinglist

**Comment by pjaudiomv** [comment]
Because the brackets are not used, this would mess up most meetinglist

**Comment by radius314** [comment]
aren't the shortcodes like `[city]` for example?

**Comment by pjaudiomv** [comment]
No it's just city no brackets. They should have been from beginning but that's not the case

**Comment by radius314** [comment]
Ah, you are right.  This should be ok for now, but eventually someone else is going to hit this bug.

**Comment by pjaudiomv** [comment]
Yes they will, should open up a separate issue to think about fixing down the road. Sunday commentary will def have a problem

**Comment by DanielWright98** [comment]
I appreciate the comments; however, I'm not a developer. So I'm still at a loss for how to correct this issue.

**Comment by pjaudiomv** [comment]
@DanielWright98 we found a solution and will release update soon.

**Comment by DanielWright98** [comment]
Cool. Thank you.

**Comment by pjaudiomv** [comment]
What website are you using bread on currently

**Comment by DanielWright98** [comment]
I'm currently using MeetingListGenerator at https://www.tampa-na.org.
I tried Bread but ended up with identical results, so I went back to MLG.

**Comment by pjaudiomv** [comment]
You should still upgrade to bread there's been a lot of enhancements but more importantly security fixes. And when we release next update it will be seem less transition to update.

**Comment by DanielWright98** [comment]
Okay. I really appreciate the help.

**Comment by pjaudiomv** [comment]
@DanielWright98 you should be able to update and it should work now https://wordpress.org/plugins/bread/

**Pull request merged**
